export class HomePageObjects {
    protected static COOKIE_ACCEPT_XPATH = `//*[@id="ccc-notify-accept"]`;
    protected static COOKIE_REJECT_XPATH = `//*[@id="ccc-notify-reject"]`;
    protected static LOGO_XPATH = `//*[@id="universal-nav-link"]/a/img`;
    protected static PRODUCTS_XPATH = `//*[@id="dx-navigation"]/div[1]`;
    protected static SUPPORT_XPATH = `//*[@id="dx-navigation"]/div[2]/a`;
    protected static RESOURCES_XPATH = `//*[@id="dx-navigation"]/div[3]/a`;
    protected static COMPANY_XPATH = `//*[@id="dx-navigation"]/div[4]/a`;
    protected static SEARCH_BOX_XPATH = `//*[@id="global-search-input"]`;
    protected static CONTACT_US_XPATH = `//*[@id="universal-nav-links-right"]/div[1]/a`;
    protected static STORE_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/a`;
    protected static LOGIN_XPATH = `//*[@id="universal-nav-links-right"]/div[3]/a`;
    protected static UP_ARROW_XPATH = `//span[@class='angles top']`;
    protected static COUNTRY_AND_LANGUAGE_XPATH = `//*[@id="universal-nav-country-language-link"]/a`;
    protected static COUNTRY_XPATH = `//div[@class='ui search selection fluid dropdown country-dropdown']//i[@class='dropdown icon']`;
    protected static COUNTRY_EDITBOX_XPATH = `//input[@class='search']`;
    protected static ENTER_XPATH = `//input[@name='launch-language-selection']`;
    protected static LANGUAGE_XPATH = `//div[@class='ui selection fluid dropdown language-dropdown']`;
    protected static MENU_XPATH = `//*[@id="universal-navigation"]/div`;
    protected static COOKIE_XPATH = `//*[@id="ccc-notify"]`;
    protected static SDS_XPATH = `//*[@id="main-container"]/div[1]/div[3]/div/div/div/a[1]`;
    protected static WEBINARS_XPATH = `//*[@id="main-container"]/div[1]/div[3]/div/div/div/a[2]`;
    protected static VIRTUAL_SHOWCASE_XPATH = `//*[@id="main-container"]/div[1]/div[3]/div/div/div/a[3]`;
    protected static EVENTS_XPATH = `//*[@id="main-container"]/div[1]/div[3]/div/div/div/a[4]`;
    protected static MY_ORDERS_XPATH = `//*[@id="main-container"]/div[1]/div[3]/div/div/div/a[5]`;
    protected static LEARN_MORE_XPATH = `//*[@id="main-container"]/div[3]/div/div[1]/div[2]/a`;
    protected static EXPLORE_NOW_XPATH = `//*[@id="main-container"]/div[3]/div/div[2]/div[1]/a`;
    protected static DISCOVER_XPATH = `//*[@id="main-container"]/div[5]/div[1]/div/div/div[3]/a`;
    protected static LEARNING_EXPLORE_XPATH = `//*[@id="main-container"]/div[6]/div[1]/div/div[2]/div/a`;
    protected static DOCUMENTATION_EXPLORE_XPATH = `//*[@id="main-container"]/div[6]/div[2]/div/div[2]/div/a`;
    protected static SUPPORT_EXPLORE_XPATH = `//*[@id="main-container"]/div[6]/div[3]/div/div[2]/div/a`;
    protected static USERNAME_EDITBOX_XPATH = `//input[@id='username']`;
    protected static PASSWORD_EDITBOX_XPATH = `//input[@id='password']`;
    protected static LOGIN_BUTTON_XPATH = `//button[@id='kc-login']`;
    protected static ENGLISH_XPATH = `//div[@data-country='English']`;
    protected static CHEMISTRY_XPATH = '//*[@id="dx-navigation"]/div[1]/div/div[2]/a[1]';
    protected static ACC_SETTING_XPATH = '//*[@id="dx-navigation"]/div[2]/div/div[2]/a[2]';
    protected static TRAINING_XPATH = '//*[@id="dx-navigation"]/div[3]/div/div[2]/a[1]';
    protected static OVERVIEW_XPATH = '//*[@id="dx-navigation"]/div[4]/div/div[2]/a[1]';
    protected static SEARCHED_XPATH = '//*[@id="search-header"]/div/label/span[1]';
    //Footer options
    protected static AUTOMATION_SYSTEMS_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[1]/a';
    protected static BLOOD_BANKING_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[2]/a';
    protected static FOOTEER_CHEMISTRY_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[3]/a';
    protected static CLINICAL_INFORMATION_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[4]/a';
    protected static HEMATOLOGY_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[5]/a';
    protected static IMMUNOASSAY_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[6]/a';
    protected static MICROBIOLOGY_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[7]/a';
    protected static PROTEIN_CHEMISTRY_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[8]/a';
    protected static URINALYSIS_XPATH = '//div[3]/div[3]/div[3]/div/div[1]/ul/li[9]/a';
    protected static ACCOUNT_XPATH = '//div[3]/div[3]/div[3]/div/div[2]/ul/li[1]/a';
    protected static FOOTER_SDS_XPATH = '//div[3]/div[3]/div[3]/div/div[2]/ul/li[2]/a';
    protected static EDUCATION_XPATH = '//div[3]/div[3]/div[3]/div/div[2]/ul/li[3]/a';
    protected static DOCUMENTATION_XPATH = '//div[3]/div[3]/div[3]/div/div[2]/ul/li[4]/a';
    protected static FOOTER_CONTACT_US_XPATH = '//div[3]/div[3]/div[3]/div/div[2]/ul/li[5]/a';
    protected static FOOTER_OVERVIEW_XPATH = '//div[3]/div[3]/div[3]/div/div[3]/ul/li[1]/a';
    protected static NEWSROOM_XPATH = '//div[3]/div[3]/div[3]/div/div[3]/ul/li[2]/a';
    protected static FOOTER_EVENTS_XPATH = '//div[3]/div[3]/div[3]/div/div[3]/ul[1]/li[3]/a';
    protected static BLOG_XPATH = '//div[3]/div[3]/div[3]/div/div[3]/ul/li[4]/a';
    protected static SUBSCRIBE_XPATH = '//ul[@class="group-links"]//a[@alt="Subscribe to our Newsletter"][normalize-space()="Subscribe to our Newsletter"]';
    protected static NEWSLETTER_XPATH = '//*[@id="main-container"]/div[2]/div/div[1]/div/div/h2';
    protected static PARITCLE_COUNTER_XPATH = "(//a[@alt='Air Particle Counters'])[1]";
    protected static CENTRIFUGATION_XPATH = '(//a[@alt="Centrifugation"])[1]';
    protected static CELL_COUNTER_XPATH = '(//a[@alt="Cell Counters & Analyzers"])[1]';
    protected static FLOW_CYTOMETRY_XPATH = '(//a[@alt="Flow Cytometry & Cell Sorting"])[1]';
    protected static LIQUID_HANDLER_XPATH = '(//a[@alt="Liquid Handlers"])[1]';
    protected static LIQUID_PARTICLE_COUNTER_XPATH = '(//a[@alt="Liquid Particle Counters"])[1]';
    protected static PARTICLE_CHARACTERIZATION_XPATH = '(//a[@alt="Particle Characterization"])[1]';
    protected static TOC_ANALYZERS_XPATH = '(//a[@alt="TOC Analyzers"])[1]';
    protected static LINKED_IN_XPATH = "(//a[@class='logo-padding'])[2]";
    protected static TWITTER_XPATH = "(//a[@class='logo-padding'])[4]";
    protected static YOUTUBE_XPATH = "(//a[@class='logo-padding'])[3]";
    protected static FACEBOOK_XPATH = "(//a[@class='logo-padding'])[5]";
    protected static REQUEST_QUOTE_XPATH = '//*[@id="RfqButton"]';
    protected static LINKEDIN_NAME_XPATH = '//*[@id="main-content"]/section[1]/section/div/div[2]/div[1]/h1';
    protected static TWITTER_NAME_XPATH = '//*[@id="react-root"]/div/div/div[2]/main/div/div/div/div/div/div[3]/div/div/div/div/div[2]/div[1]/div/div[1]/div/div/span[1]/span';
    protected static YOUTUBE_NAME_XPATH = '(//*[@id="text"])[1]';
    protected static FACEBOOK_NAME_XPATH = '//*[@id="mount_0_0_8b"]/div/div[1]/div/div[3]/div/div/div/div[1]/div[1]/div/div/div[1]/div[2]/div/div/div/div[3]/div/div/div[1]/div/div/span/div/h1';
    //Contact us page objects
    protected static AGREE_XPATH = `//a[@aria-label='dismiss cookie message']`;
    protected static INQUIRY_TYPE_XPATH = `//div[3]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div/div[2]/div[2]/div[2]/div`;
    protected static PRODUCT_NAME_XPATH = `//div[3]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div/div[2]/div[2]/div[3]/div[1]/div/div[1]`;
    protected static CONSUMABLE_XPATH = `//*[@id='consumable']`;
    protected static HARDWARE_XPATH = `//*[@id='consumable']`;
    protected static SALUTATION_XPATH = `//*[contains(@class,'ui fluid dropdown selection')]`;
    protected static FIRST_NAME_XPATH = `//*[@name='firstName']`;
    protected static LAST_NAME_XPATH = `//*[contains(@name,'lastName')]`;
    protected static EMAIL_XPATH = `//*[contains(@name,'email')]`;
    protected static PHONE_NUMBER_XPATH = `//*[contains(@name,'phoneNumber')]`;
    protected static COMPANYY_NAME_XPATH = `//*[contains(@name,'companyName')]`;
    protected static DEPARTMENT_XPATH = `//*[contains(@name,'department')]`;
    protected static ADDRESS1_XPATH = `//*[@name='address1']`;
    protected static ADDRESS2_XPATH = `//*[@name='address2']`;
    protected static CITY_XPATH = `//*[@name='city']`;
    protected static POSTAL_CODE_XPATH = `//*[@name='postalCode']`;
    protected static JOB_TITLE_XPATH = `//*[@id="account-details"]/div[11]/div/div[1]`;
    protected static QUESTION_XPATH = `//*[@name='comments']`;
    protected static EMAIL_CONSENT_XPATH = `//*[@for='email-consent-in']`;
    protected static EMAIL_DO_NOT_CONSENT_XPATH = `//*[@for='email-consent-out']`;
    protected static PHONE_CONSENT_XPATH = `//*[@for='phone-consent-in']`;
    protected static PHONE_DO_NOT_CONSENT_XPATH = `//*[@for='phone-consent-out']`;
    protected static TERMS_XPATH = `//*[@id='terms']`;
    protected static CAPTCHA_XPATH = `//*[@id='recaptcha1']`;
    protected static SUBMIT_BUTTON_XPATH = `//*[@class='ui primary submit button']`;
    protected static SDS_xPATH = `//*[@id="account-details"]/div[2]/div/div[2]/div[2]`;
    protected static TECHNICAL_SUPPORT_XPATH = `//*[@id="account-details"]/div[2]/div/div[2]/div[3]`;
    protected static PRODUCT_TRAINING_XPATH = `//*[@id="account-details"]/div[2]/div/div[2]/div[4]`;
    protected static PRODUCT_WARRANTIES_XPATH = `//*[@id="account-details"]/div[2]/div/div[2]/div[5]`;
    protected static PRODUCT_CHEMISTRY_XPATH = `//*[@id="inquiry-product-line"]/div[1]/div/div[2]/div[1]`;
    protected static PRODUCT_CYTOMETRY_XPATH = `//*[@id="inquiry-product-line"]/div[1]/div/div[2]/div[2]`;
    protected static PRODUCT_HEMATOLOGY_XPATH = `//*[@id="inquiry-product-line"]/div[1]/div/div[2]/div[3]`;
    protected static PRODUCT_IMMUNOASSAY_XPATH = `//*[@id="inquiry-product-line"]/div[1]/div/div[2]/div[4]`;
    protected static DR_XPATH = `//*[@id="account-details"]/div[4]/div/div[2]/div[1]`;
    protected static MR_XPATH = `//*[@id="account-details"]/div[4]/div/div[2]/div[3]`;
    protected static MRS_XPATH = `//*[@id="account-details"]/div[4]/div/div[2]/div[2]`;
    protected static PROFESSOR_XPATH = `//*[@id="account-details"]/div[4]/div/div[2]/div[4]`;
    protected static C_SUITE_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[1]`;
    protected static CLINICAL_CHEMIST_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[2]`;
    protected static CONSULTANT_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[3]`;
    protected static ED_NURSE_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[4]`;
    protected static ED_PHYSICIAN_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[5]`;
    protected static HOSPITAL_ADMINISTRATION_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[6]`;
    protected static INFORMATION_TECHNOLOGY_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[7]`
    protected static INFORMATION_TECHNOLOGY_DIRECTOR_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[8]`
    protected static INFORMATION_TECHNOLOGY_MANAGER_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[9]`
    protected static LAB_ANALYST_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[10]`;
    protected static LAB_ASSISTANT_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[11]`;
    protected static LAB_COORDINATOR_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[12]`;
    protected static LAB_DIRECTOR_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[13]`;
    protected static LAB_MANAGER_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[14]`
    protected static LAB_OPERATIONS_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[15]`;
    protected static LAB_PHYSICIAN_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[16]`
    protected static LAB_SPECIALIST_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[17]`;
    protected static LAB_STAFF_MANAGER_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[18]`;
    protected static LAB_SUPERVISOR_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[19]`;
    protected static LAB_TECHNICIAN_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[20]`;
    protected static MEDICALL_DIRECTOR_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[21]`
    protected static MEDICAL_TECHNOLOGIST_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[22]`;
    protected static OTHER_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[23]`;
    protected static PATHOLOGIST_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[24]`;
    protected static PHYSICIAN_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[25]`;
    protected static SCIENTIST_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[26]`;
    protected static STUDENT_PROFESSOR_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[27]`;
    protected static UROLOGIST_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[28]`;
    protected static VETERINARIAN_XPATH = `//*[@id="account-details"]/div[11]/div/div[2]/div[29]`;
    protected static SUCCESS_XPATH = '//*[@id="inquiry-successful"]';
    protected static ERROR_XPATH = '//*[@id="account-details"]/div[16]/ul/li';
    //Store objects
    protected static USERNAME_EDITBOX_ID = `#username`;
    protected static PASSWORD_EDITBOX_ID = `#password`;
    protected static LOGIN_BUTTON_ID = `#kc-login`;
    protected static ITEM_NUMBER_XPATH = `//*[@id="itemNumber"]`;
    protected static ADD_TO_CART_XPATH = `//*[@id="disableMultiCartId"]`;
    protected static CHECK_OUT_XPATH = `//*[@id="ssoLogin"]`;
    protected static ORDER_AND_STATUS_TRACKING_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/div/a[1]`;
    protected static SCHEDULED_ORDERS_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/div/a[2]`;
    protected static QUICK_ORDERS_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/div/a[3]`;
    protected static SHOPPING_LIISTS_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/div/a[4]`;
    protected static INVOICES_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/div/a[5]`;
    protected static SHOPPING_FAQS_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/div/a[6]`;
    protected static QUOTE_REQUESTS_XPATH = `//*[@id="universal-nav-links-right"]/div[2]/div/a[7]`;
    protected static STORE_ENTER_XPATH = `//input[@name='launch-language-selection']`;
    protected static MODULE_XPATH = '//*[@id="container"]/div/p';
    protected static ACC_SUPPORT_XPATH = '//*[@id="main-container"]/div/div/div/h2/p[1]';
    protected static CUSTOMER_ACC_NUM_XPATH = '//*[@id="custAccNumber"]';
    protected static ITEM_XPATH = '//*[@id="item-no"]';
    protected static SEARCH_RESULT_XPATH = '//div[3]/div[2]/div/div[1]/div[3]/div[2]/div[3]/div[1]/a/div';
}