export class ProductsPageObjects {
    protected static COOKIE_ACCEPT_XPATH = `//*[@id="ccc-notify-accept"]`;
    protected static COOKIE_REJECT_XPATH = `//*[@id="ccc-notify-reject"]`;
    protected static IMAGE_1_XPATH = `//*[@id="main-container"]/div[2]/div/div[1]/div/div[2]/div/div[1]/img`;
    protected static IMAGE_2_XPATH = `//*[@id="main-container"]/div[2]/div/div[1]/div/div[2]/div/div[2]/img`;
    protected static IMAGE_3_XPATH = `//*[@id="main-container"]/div[2]/div/div[1]/div/div[2]/div/div[3]/img`;
    protected static IMAGE_4_XPATH = `//*[@id="main-container"]/div[2]/div/div[1]/div/div[2]/div/div[4]/img`;
    protected static IMAGE_5_XPATH = `//*[@id="main-container"]/div[2]/div/div[1]/div/div[2]/div/div[5]/img`;
    protected static REQUESTMORE_XPATH = `//*[@id="main-container"]/div[2]/div/div[2]/div[4]/div/div/a`;
    protected static SPECIFICATIONS_XPATH = `//a[@id='tab-specifications']`;
    protected static TEST_MENU_XPATH = `//a[@id='tab-test-menu']`;
    protected static DOCUMENTS_XPATH = `//*[@id="tab-documents"]`;
    protected static USER_GUIDE_XPATH = `(//*[@id="Layer_1"])[1]`;
    protected static REQUEST_QUOTE_XPATH = `//*[@id="main-container"]/div[3]/div/div/div/div/div[5]/div/div[3]/div[1]/div/div[2]/a[1]`;
    protected static ADD_TO_CART_XPATH = `//*[@id="main-container"]/div[3]/div/div/div/div/div[5]/div/div[3]/div[1]/div/div[2]/a[2]`;
    protected static SHARE_XPATH = `//*[@id="main-container"]/div[1]/div/div[2]/div/div[1]`;
    protected static PAGENUM_FIRST_XPATH = `//*[@id="main-container"]/div[3]/div/div/div/div/div[5]/div/div[2]/div[1]`;
    protected static PAGENUM_BEFORE_XPATH = `//*[@id="main-container"]/div[3]/div/div/div/div/div[5]/div/div[2]/div[2]`;
    protected static PAGENUM_NEXT_XPATH = `//*[@id="main-container"]/div[3]/div/div/div/div/div[5]/div/div[2]/div[3]`;
    protected static PAGENUM_LAST_XPATH = `//*[@id="main-container"]/div[3]/div/div/div/div/div[5]/div/div[2]/div[4]`;
    protected static QUICK_RESPONSE_GUIDE_XPATH = `//*[@id="main-container"]/div[3]/div/div/div/div/div[8]/div[2]/div/div[3]/div/div/table/tbody/tr/td[3]/div/div/a/span`;
    protected static INFO_REQUEST_XPATH = '//div[6]/div/div[1]/h4';
    protected static DOWNLOAD_XPATH = '//div[2]/div[2]/div[2]/div/div/div/a';
    protected static SHARE_FACEBOOK_XPATH = '//div[3]/div[2]/div[1]/div/div[2]/div/div[2]/div/ul/li[3]/a/img';
    protected static SHARE_TWITTER_XPATH = '//div[3]/div[2]/div[1]/div/div[2]/div/div[2]/div/ul/li[2]/a/img';
    protected static SHARE_LINKEDIN_XPATH = '//div[3]/div[2]/div[1]/div/div[2]/div/div[2]/div/ul/li[1]/a/img';
    protected static SHARE_ENVLOPE_XPATH = '//div[3]/div[2]/div[1]/div/div[2]/div/div[2]/div/ul/li[4]/a/img';
    protected static ITEM_NUMBER_XPATH = '//div[6]/div/div[2]/div[2]/form/table/tbody/tr[1]/td[1]';
    protected static SPECIFICATION_COLUMN_1_XPATH = '//div[3]/div[2]/div[3]/div/div/div/div/div[4]/div/table/tbody/tr[1]/td[1]/h4'
}